dist: bionic 

language: cpp

matrix:
  include:
    # Compilation with gcc
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - python3
            - ninja-build
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    # Compilation with clang
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - clang++-9
            - python3
            - ninja-build
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip3.6 install conan
  - conan user

branches:
  only:
    - main
    - conan-and-catch-integration

script:
  - python3 ./ci/build.py --install --type release
  - python3 ./ci/tests.py --type release
