dist: bionic 

language: cpp

matrix:
  include:
    # Compilation with gcc
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - llvm10
            - clang++-10
            - python3
            - ninja-build
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"

    # Compilation with clang
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - llvm10
            - clang++-10
            - python3
            - ninja-build
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

before_install:
  - eval "${MATRIX_EVAL}"

branches:
  only:
    - main

script:
  - python3 ./tools/ci/build.py --type release
  - python3 ./tools/ci/tests.py --type release
