string(COMPARE EQUAL ${ENABLE_CLANG_TIDY} true enable_clang_tidy)

if(enable_clang_tidy)
	message("-- Enable clang-tidy analyse")
	find_program(CLANGTIDY clang-tidy)
	if(CLANGTIDY)
		set(CMAKE_CXX_CLANG_TIDY ${CLANGTIDY} -extra-arg=-Wno-unknown-warning-option)
	else()
		message(SEND_ERROR "clang-tidy requested but executable not found")
	endif()
endif()
